### ISSUE TITLE
Error thrown using debug world with vector_math > 1.4.3

### ISSUE THREAD

**Issue by benoitletondor** [google/box2d.dart#2]
Hello there.

I have this error being thrown using any version of vector_math superior to 1.4.3. Seems that is related to box2d and it works perfectly using vector_math 1.4.3.

> Uncaught Unhandled exception:
> 'package:box2d/src/common/transform.dart': Failed assertion: line 91 pos 12: 'v != out' is not true.
> 0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
> 1      Transform.mulToOutUnsafeVec2 (package:box2d/src/common/transform.dart:91:12)
> 2      World.drawShape (package:box2d/src/dynamics/world.dart:1501:23)
> 3      World.drawDebugData (package:box2d/src/dynamics/world.dart:662:13)

Thanks in advance for looking at it, and thank you for the good work done :)

**Comment by johnmccutchan** [comment]
This is fixed in Git. Will publish box2d 0.3.0 later today.
